import  unittest
from selenium import webdriver
import time
from selenium.webdriver import ActionChains



class Testiranje(unittest.TestCase):

    def setUp(self):
        self.driver=webdriver.Firefox()
        self.driver.implicitly_wait(5)
        self.driver.maximize_window()

    def test1(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("21")
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test2(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("21")
        time.sleep(1)
        ga = driver.find_element_by_xpath("//a[@class='navbar-brand router-link-exact-active router-link-active']")
        ga.click()
        driver.close()

    def test3(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("21")
        time.sleep(1)
        ag = driver.find_element_by_xpath("//a[@class='nav-link nav-buttons router-link-exact-active router-link-active']")
        ag.click()
        driver.close()

    def test4(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test5(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("21")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test6(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test7(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        lm = driver.find_element_by_xpath("//button[@class='btn btn-custom']")
        lm.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test8(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        lm = driver.find_element_by_xpath("//button[@class='btn btn-custom']")
        lm.click()
        time.sleep(1)
        lm.click()
        time.sleep(1)
        driver.refresh()
        time.sleep(1)
        driver.close()

    def test9(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        ugn = driver.find_element_by_xpath("//a[contains(text(),'user.gallery_name')]")
        ugn.click()
        time.sleep(1)
        driver.close()

    def test10(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        tt = driver.find_element_by_xpath("//a[contains(text(),'Testonja Testic')]")
        tt.click()
        time.sleep(1)
        driver.close()


    def test11(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        tt = driver.find_element_by_xpath("//a[contains(text(),'Testonja Testic')]")
        tt.click()
        time.sleep(1)
        ag=driver.find_element_by_xpath("//a[@class='nav-link nav-buttons router-link-active']")
        ag.click()
        time.sleep(1)
        driver.close()

    def test12(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        tt = driver.find_element_by_xpath("//a[contains(text(),'Testonja Testic')]")
        tt.click()
        time.sleep(1)
        t1=driver.find_element_by_xpath("//a[contains(text(),'T1')]")
        t1.click()
        time.sleep(1)
        driver.close()

    def test13(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.implicitly_wait(10)
        driver.get(r"https://gallery-app.vivifyideas.com/")
        time.sleep(1)
        labela = driver.find_element_by_xpath("//input[@placeholder='Search...']")
        labela.send_keys("all")
        time.sleep(1)
        fil = driver.find_element_by_xpath("//button[@class='btn btn-outline-secondary input-button']")
        fil.click()
        time.sleep(1)
        tt = driver.find_element_by_xpath("//a[contains(text(),'Testonja Testic')]")
        tt.click()
        time.sleep(1)
        ug=driver.find_element_by_xpath("//a[contains(text(),'user.gallery_name')]")
        ug.click()
        time.sleep(1)
        b1=driver.find_element_by_xpath("//span[@class='carousel-control-next-icon']")
        b1.click()
        time.sleep(1)
        driver.close()

    def tearDown(self):
        self.driver.close()